//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.segue` struct is generated, and contains static references to 2 view controllers.
  struct segue {
    /// This struct is generated for `DrawViewController`, and contains static references to 2 segues.
    struct drawViewController {
      /// Segue identifier `CreditsSegue`.
      static let creditsSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, DrawViewController, CreditsTableViewController> = Rswift.StoryboardSegueIdentifier(identifier: "CreditsSegue")
      /// Segue identifier `SpectrogramSegue`.
      static let spectrogramSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, DrawViewController, SpectrogramViewController> = Rswift.StoryboardSegueIdentifier(identifier: "SpectrogramSegue")

      #if os(iOS) || os(tvOS)
      /// Optionally returns a typed version of segue `CreditsSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func creditsSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, DrawViewController, CreditsTableViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.drawViewController.creditsSegue, segue: segue)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// Optionally returns a typed version of segue `SpectrogramSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func spectrogramSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, DrawViewController, SpectrogramViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.drawViewController.spectrogramSegue, segue: segue)
      }
      #endif

      fileprivate init() {}
    }

    /// This struct is generated for `StartViewController`, and contains static references to 2 segues.
    struct startViewController {
      /// Segue identifier `DrawSegue`.
      static let drawSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, StartViewController, DrawViewController> = Rswift.StoryboardSegueIdentifier(identifier: "DrawSegue")
      /// Segue identifier `SpectrogramSegue`.
      static let spectrogramSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, StartViewController, SpectrogramViewController> = Rswift.StoryboardSegueIdentifier(identifier: "SpectrogramSegue")

      #if os(iOS) || os(tvOS)
      /// Optionally returns a typed version of segue `DrawSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func drawSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, StartViewController, DrawViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.startViewController.drawSegue, segue: segue)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// Optionally returns a typed version of segue `SpectrogramSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func spectrogramSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, StartViewController, SpectrogramViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.startViewController.spectrogramSegue, segue: segue)
      }
      #endif

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 17 files.
  struct file {
    /// Resource file `Pattern-Poem-Maze.jpg`.
    static let patternPoemMazeJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "Pattern-Poem-Maze", pathExtension: "jpg")
    /// Resource file `divina_commedia.json`.
    static let divina_commediaJson = Rswift.FileResource(bundle: R.hostingBundle, name: "divina_commedia", pathExtension: "json")
    /// Resource file `page-1.txt`.
    static let page1Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-1", pathExtension: "txt")
    /// Resource file `page-10.txt`.
    static let page10Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-10", pathExtension: "txt")
    /// Resource file `page-11.txt`.
    static let page11Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-11", pathExtension: "txt")
    /// Resource file `page-12.txt`.
    static let page12Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-12", pathExtension: "txt")
    /// Resource file `page-13.txt`.
    static let page13Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-13", pathExtension: "txt")
    /// Resource file `page-14.txt`.
    static let page14Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-14", pathExtension: "txt")
    /// Resource file `page-15.txt`.
    static let page15Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-15", pathExtension: "txt")
    /// Resource file `page-2.txt`.
    static let page2Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-2", pathExtension: "txt")
    /// Resource file `page-3.txt`.
    static let page3Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-3", pathExtension: "txt")
    /// Resource file `page-4.txt`.
    static let page4Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-4", pathExtension: "txt")
    /// Resource file `page-5.txt`.
    static let page5Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-5", pathExtension: "txt")
    /// Resource file `page-6.txt`.
    static let page6Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-6", pathExtension: "txt")
    /// Resource file `page-7.txt`.
    static let page7Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-7", pathExtension: "txt")
    /// Resource file `page-8.txt`.
    static let page8Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-8", pathExtension: "txt")
    /// Resource file `page-9.txt`.
    static let page9Txt = Rswift.FileResource(bundle: R.hostingBundle, name: "page-9", pathExtension: "txt")

    /// `bundle.url(forResource: "Pattern-Poem-Maze", withExtension: "jpg")`
    static func patternPoemMazeJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.patternPoemMazeJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "divina_commedia", withExtension: "json")`
    static func divina_commediaJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.divina_commediaJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-1", withExtension: "txt")`
    static func page1Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page1Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-10", withExtension: "txt")`
    static func page10Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page10Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-11", withExtension: "txt")`
    static func page11Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page11Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-12", withExtension: "txt")`
    static func page12Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page12Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-13", withExtension: "txt")`
    static func page13Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page13Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-14", withExtension: "txt")`
    static func page14Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page14Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-15", withExtension: "txt")`
    static func page15Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page15Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-2", withExtension: "txt")`
    static func page2Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page2Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-3", withExtension: "txt")`
    static func page3Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page3Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-4", withExtension: "txt")`
    static func page4Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page4Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-5", withExtension: "txt")`
    static func page5Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page5Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-6", withExtension: "txt")`
    static func page6Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page6Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-7", withExtension: "txt")`
    static func page7Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page7Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-8", withExtension: "txt")`
    static func page8Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page8Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "page-9", withExtension: "txt")`
    static func page9Txt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.page9Txt
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 5 images.
  struct image {
    /// Image `Pattern-Poem-Maze.jpg`.
    static let patternPoemMazeJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "Pattern-Poem-Maze.jpg")
    /// Image `air`.
    static let air = Rswift.ImageResource(bundle: R.hostingBundle, name: "air")
    /// Image `gesture`.
    static let gesture = Rswift.ImageResource(bundle: R.hostingBundle, name: "gesture")
    /// Image `launch`.
    static let launch = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch")
    /// Image `stop`.
    static let stop = Rswift.ImageResource(bundle: R.hostingBundle, name: "stop")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Pattern-Poem-Maze.jpg", bundle: ..., traitCollection: ...)`
    static func patternPoemMazeJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.patternPoemMazeJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "air", bundle: ..., traitCollection: ...)`
    static func air(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.air, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "gesture", bundle: ..., traitCollection: ...)`
    static func gesture(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gesture, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "launch", bundle: ..., traitCollection: ...)`
    static func launch(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "stop", bundle: ..., traitCollection: ...)`
    static func stop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stop, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"
            static let uiSceneStoryboardFile = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneStoryboardFile") ?? "Main"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 4 localization keys.
    struct localizable {
      /// Value: App requires microphone access.
      static let requiresMicrophoneAccess = Rswift.StringResource(key: "requiresMicrophoneAccess", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Can't create microphone.
      static let cantCreateMicrophone = Rswift.StringResource(key: "cantCreateMicrophone", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Error
      static let errorTitle = Rswift.StringResource(key: "errorTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Something went wrong: 
      static let errorMessage = Rswift.StringResource(key: "errorMessage", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: App requires microphone access.
      static func requiresMicrophoneAccess(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("requiresMicrophoneAccess", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "requiresMicrophoneAccess"
        }

        return NSLocalizedString("requiresMicrophoneAccess", bundle: bundle, comment: "")
      }

      /// Value: Can't create microphone.
      static func cantCreateMicrophone(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("cantCreateMicrophone", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "cantCreateMicrophone"
        }

        return NSLocalizedString("cantCreateMicrophone", bundle: bundle, comment: "")
      }

      /// Value: Error
      static func errorTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("errorTitle", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "errorTitle"
        }

        return NSLocalizedString("errorTitle", bundle: bundle, comment: "")
      }

      /// Value: Something went wrong: 
      static func errorMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("errorMessage", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "errorMessage"
        }

        return NSLocalizedString("errorMessage", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "launch", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'launch' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = StartViewController

      let bundle = R.hostingBundle
      let name = "Main"

      static func validate() throws {
        if UIKit.UIImage(named: "air", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'air' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "gesture", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'gesture' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "stop", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'stop' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "xmark") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'xmark' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
